# Generated by Django 4.2.5 on 2023-10-09 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('degree_checklist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='CourseId',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='course',
            name='PreRequisiteCourseId',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='degreeplan',
            name='CourseId1',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='degreeplan',
            name='CourseId2',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='student',
            name='StudentId',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='studentcourse',
            name='CourseId',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='studentcourse',
            name='StudentId',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='studentdegree',
            name='StudentId',
            field=models.CharField(max_length=250),
        ),
    ]
