# Generated by Django 4.2.5 on 2023-11-02 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('degree_checklist', '0002_alter_course_courseid_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DepartmententId', models.IntegerField()),
                ('Name', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProgramId', models.IntegerField()),
                ('Name', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='ProgramCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProgramId', models.IntegerField()),
                ('CourseId', models.CharField(max_length=250)),
            ],
        ),
        migrations.RenameModel(
            old_name='StudentDegree',
            new_name='College',
        ),
        migrations.DeleteModel(
            name='DegreePlan',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
        migrations.DeleteModel(
            name='StudentCourse',
        ),
        migrations.RenameField(
            model_name='college',
            old_name='DegreeId',
            new_name='CollegeId',
        ),
        migrations.RenameField(
            model_name='college',
            old_name='StudentId',
            new_name='Name',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='CourseName',
            new_name='IsCore',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='PreRequisiteCourseId',
            new_name='IsMajor',
        ),
        migrations.AddField(
            model_name='course',
            name='Name',
            field=models.CharField(default='', max_length=250),
        ),
    ]
