# Generated by Django 4.2.5 on 2023-11-16 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('degree_checklist', '0003_department_program_programcourse_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='CollegeId',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='program',
            name='DepartmententId',
            field=models.IntegerField(default=0),
        ),
    ]
