# Generated by Django 4.2.5 on 2023-11-16 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('degree_checklist', '0004_department_collegeid_program_departmententid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='college',
            name='id',
        ),
        migrations.RemoveField(
            model_name='course',
            name='id',
        ),
        migrations.RemoveField(
            model_name='department',
            name='id',
        ),
        migrations.RemoveField(
            model_name='program',
            name='id',
        ),
        migrations.AlterField(
            model_name='college',
            name='CollegeId',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='course',
            name='CourseId',
            field=models.CharField(max_length=250, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='department',
            name='DepartmententId',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='program',
            name='ProgramId',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
